package news.newspublish.model;

public class Clue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.content
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.create_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.audit1
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long audit1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.audit1_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long audit1No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.audit2
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long audit2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.audit2_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long audit2No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.to_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.status
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.type
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.gmt_create
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.gmt_modified
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.title
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.return_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long returnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.img_flag
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private Long imgFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.img
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.id
     *
     * @return the value of clue.id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.id
     *
     * @param id the value for clue.id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.content
     *
     * @return the value of clue.content
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.content
     *
     * @param content the value for clue.content
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.create_id
     *
     * @return the value of clue.create_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.create_id
     *
     * @param createId the value for clue.create_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.audit1
     *
     * @return the value of clue.audit1
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getAudit1() {
        return audit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.audit1
     *
     * @param audit1 the value for clue.audit1
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setAudit1(Long audit1) {
        this.audit1 = audit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.audit1_no
     *
     * @return the value of clue.audit1_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getAudit1No() {
        return audit1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.audit1_no
     *
     * @param audit1No the value for clue.audit1_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setAudit1No(Long audit1No) {
        this.audit1No = audit1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.audit2
     *
     * @return the value of clue.audit2
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getAudit2() {
        return audit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.audit2
     *
     * @param audit2 the value for clue.audit2
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setAudit2(Long audit2) {
        this.audit2 = audit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.audit2_no
     *
     * @return the value of clue.audit2_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getAudit2No() {
        return audit2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.audit2_no
     *
     * @param audit2No the value for clue.audit2_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setAudit2No(Long audit2No) {
        this.audit2No = audit2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.to_id
     *
     * @return the value of clue.to_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.to_id
     *
     * @param toId the value for clue.to_id
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setToId(Long toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.status
     *
     * @return the value of clue.status
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.status
     *
     * @param status the value for clue.status
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.type
     *
     * @return the value of clue.type
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.type
     *
     * @param type the value for clue.type
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.gmt_create
     *
     * @return the value of clue.gmt_create
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.gmt_create
     *
     * @param gmtCreate the value for clue.gmt_create
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.gmt_modified
     *
     * @return the value of clue.gmt_modified
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.gmt_modified
     *
     * @param gmtModified the value for clue.gmt_modified
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.title
     *
     * @return the value of clue.title
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.title
     *
     * @param title the value for clue.title
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.return_no
     *
     * @return the value of clue.return_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getReturnNo() {
        return returnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.return_no
     *
     * @param returnNo the value for clue.return_no
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setReturnNo(Long returnNo) {
        this.returnNo = returnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.img_flag
     *
     * @return the value of clue.img_flag
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public Long getImgFlag() {
        return imgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.img_flag
     *
     * @param imgFlag the value for clue.img_flag
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setImgFlag(Long imgFlag) {
        this.imgFlag = imgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.img
     *
     * @return the value of clue.img
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.img
     *
     * @param img the value for clue.img
     *
     * @mbg.generated Sat May 23 17:47:34 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}