package news.newsworker.model;

public class Iplog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.user_id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.ip
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.login_time
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    private Long loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.status
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    private Long status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.id
     *
     * @return the value of iplog.id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.id
     *
     * @param id the value for iplog.id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.user_id
     *
     * @return the value of iplog.user_id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.user_id
     *
     * @param userId the value for iplog.user_id
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.ip
     *
     * @return the value of iplog.ip
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.ip
     *
     * @param ip the value for iplog.ip
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.login_time
     *
     * @return the value of iplog.login_time
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public Long getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.login_time
     *
     * @param loginTime the value for iplog.login_time
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.status
     *
     * @return the value of iplog.status
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.status
     *
     * @param status the value for iplog.status
     *
     * @mbg.generated Mon May 18 01:37:09 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }
}